# Generated by Django 2.2.1 on 2019-05-31 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20190530_2133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='created_date',
            new_name='created_at',
        ),
    ]
